---
language: c++
dist: xenial

compiler:
  - clang
  - gcc

install:
  - sudo apt-get update || true
  - sudo apt-get install build-essential

before_script:
  - git clone https://github.com/ntop/n2n.git; cd n2n; ./autogen.sh; make; cd ..
  - ./autogen.sh

script:
  - ./configure
  - make

notifications:
  email:
    recipients:
      - deri@ntop.org
    on_success: never
    on_failure: always
