/* automatically generated by rust-bindgen 0.59.2 */

extern "C" {
    pub fn quick_edge_init(
        device_name: *mut ::std::os::raw::c_char,
        community_name: *mut ::std::os::raw::c_char,
        encrypt_key: *mut ::std::os::raw::c_char,
        device_mac: *mut ::std::os::raw::c_char,
        local_ip_address: *mut ::std::os::raw::c_char,
        supernode_ip_address_port: *mut ::std::os::raw::c_char,
        keep_on_running: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
